version: '3.4'

volumes:
  iotomatoes_supportpackage:
    name: iotomatoes_supportpackage
    external: true

services:
  device1:
    image: device1
    build:
      context: .
      dockerfile: ./Device1/Dockerfile
    network_mode: "bridge"
    volumes:
      - iotomatoes_supportpackage:/app/iotomatoes_supportpackage

  device2:
    image: device2
    build:
      context: .
      dockerfile: ./Device2/Dockerfile
    network_mode: "bridge"
    volumes:
      - iotomatoes_supportpackage:/app/iotomatoes_supportpackage

  device3:
    image: device3
    build:
      context: .
      dockerfile: ./Device3/Dockerfile
    network_mode: "bridge"
    volumes:
      - iotomatoes_supportpackage:/app/iotomatoes_supportpackage

  device4:
    image: device4
    build:
      context: .
      dockerfile: ./Device4/Dockerfile
    network_mode: "bridge"
    volumes:
      - iotomatoes_supportpackage:/app/iotomatoes_supportpackage

  device5:
    image: device5
    build:
      context: .
      dockerfile: ./Device5/Dockerfile
    network_mode: "bridge"
    volumes:
      - iotomatoes_supportpackage:/app/iotomatoes_supportpackage

  truck1:
    image: truck1
    build:
      context: .
      dockerfile: ./Truck1/Dockerfile
    network_mode: "bridge"
    volumes:
      - iotomatoes_supportpackage:/app/iotomatoes_supportpackage

  truck2:
    image: truck2
    build:
      context: .
      dockerfile: ./Truck2/Dockerfile
    network_mode: "bridge"
    volumes:
      - iotomatoes_supportpackage:/app/iotomatoes_supportpackage