version: '3.4'

volumes:
  iotomatoes_supportpackage:
    name: iotomatoes_supportpackage
    driver: local
    driver_opts:
      type: none
      device: /home/matte/Desktop/PoliTO/ProgrammingIOT/IoTomatoes/IoTomatoes_SupportPackage/src/iotomatoes_supportpackage/
      o: bind

services:
  device1:
    image: device1
    build:
      context: .
      dockerfile: ./Device1/Dockerfile
    ports:
      - "9082:9082"
    volumes:
      - iotomatoes_supportpackage:/app/iotomatoes_supportpackage

  device2:
    image: device2
    build:
      context: .
      dockerfile: ./Device2/Dockerfile
    ports:
      - "9083:9083"
    volumes:
      - iotomatoes_supportpackage:/app/iotomatoes_supportpackage

  device3:
    image: device3
    build:
      context: .
      dockerfile: ./Device3/Dockerfile
    ports:
      - "9084:9084"
    volumes:
      - iotomatoes_supportpackage:/app/iotomatoes_supportpackage

  device4:
    image: device4
    build:
      context: .
      dockerfile: ./Device4/Dockerfile
    ports:
      - "9085:9085"
    volumes:
      - iotomatoes_supportpackage:/app/iotomatoes_supportpackage

  device5:
    image: device5
    build:
      context: .
      dockerfile: ./Device5/Dockerfile
    ports:
      - "9086:9086"
    volumes:
      - iotomatoes_supportpackage:/app/iotomatoes_supportpackage

  truck1:
    image: truck1
    build:
      context: .
      dockerfile: ./Truck1/Dockerfile
    ports:
      - "9087:9087"
    volumes:
      - iotomatoes_supportpackage:/app/iotomatoes_supportpackage

  truck2:
    image: truck2
    build:
      context: .
      dockerfile: ./Truck2/Dockerfile
    ports:
      - "9088:9088"
    volumes:
      - iotomatoes_supportpackage:/app/iotomatoes_supportpackage